spring:
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: 123456
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲时间
        min-idle: 0
        # 连接池中最大空闲连接
        max-idle: 8
        # 连接池中的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负数表示没有限制）
        max-wait: -1ms
nh:
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.nh.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml